kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "test-pipeline"
spec:
  env:
    - name: "test-sa"
      value: "moje-demo"
  source:
    git:
      uri: "https://github.com/janNevedel/testpipeline.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline

